logout:
    path: /logout
    methods: GET

login:
  path: /login
  controller: App\Controller\SecurityController::login

mood.today:
    path: /mood/today
    controller: App\Controller\MoodController::moodToday
