index:
    path: /
    controller: App\Controller\HomeController::index

booking.calendar:
    path: /calendar
    controller: App\Controller\BookingController::calendar

booking.loadEvent:
    path: /loadEvent/{id}
    controller: App\Controller\BookingController::loadOneEvent
    options:
        expose: true

dropUpdate:
    path: /dropUpdate/{id}
    controller: App\Controller\BookingController::dropUpdate
    options:
        expose: true
