index:
    path: /
    controller: App\Controller\BookingController::index

dropUpdate:
    path: /dropUpdate/{id}
    controller: App\Controller\BookingController::dropUpdate
    options:
        expose: true
