index:
    path: /bujo
    controller: App\Controller\HomeController::index

logout:
    path: /logout
    methods: GET

login:
  path: /login
  controller: App\Controller\SecurityController::login
  
booking.calendar:
    path: /calendar
    controller: App\Controller\BookingController::calendar

booking.loadEvent:
    path: /loadEvent/{id}
    controller: App\Controller\BookingController::loadOneEvent
    options:
        expose: true

dropUpdate:
    path: /dropUpdate/{id}
    controller: App\Controller\BookingController::dropUpdate
    options:
        expose: true

mood.today:
    path: /mood/today
    controller: App\Controller\MoodController::moodToday
